### PR TITLE
Support rmarkdown

### PR DESCRIPTION
**Pull request by TudorAndrei**
Implemented support for rMarkdown files

### CODE REVIEW

**Comment by mehalter** [comment]
Could this please get merged! This would be very useful as I write a lot of Rmarkdown and it follows Pandoc crossref!

**Comment by TudorAndrei** [comment]
@mehalter If you want just use my [fork](https://github.com/TudorAndrei/cmp-pandoc-references) for the time being, until @jc-doyle merges.

**Comment by mehalter** [comment]
That's what I'm doing @TudorAndrei 😂 Thanks!

**Comment by jc-doyle** [comment]
Completely missed this - thanks @TudorAndrei

**Pull request merged**
